### ISSUE TITLE
Task falls with error after it's update

### ISSUE THREAD

**Issue by Skvorecz** [dmitryserbin/azdev-artifacts-tagger#12]
After update to version _1.2.926_ task always throws an error:

> ##[error]No pipeline artifacts detected

**Comment by dmitryserbin** [comment]
That is expected when you don't have any build artifacts in your release pipeline

<img width="684" alt="image" src="https://user-images.githubusercontent.com/30379061/133509320-dccb2961-982f-4c04-86d8-2d639908f58e.png">

**Comment by Skvorecz** [comment]
The thing is that I started receiving this errors right after task update without changing anything in the pipeline.
I will recheck artifacts tomorrow anyway and let you know.

**Comment by Skvorecz** [comment]
You are showing an example from release pipeline, but I use the task in the regular pipeline.
My pipeline publish artifacts and then it runs Artifacts Tagger which I expect to tag published artifacts (just as it worked on version 1.1.2).

**Comment by dmitryserbin** [comment]
Right, I think I know what's going on. Is that classic or yaml build pipeline? If you could post a screenshot that would be great.

**Comment by Skvorecz** [comment]
A classic pipeline

![pipeline](https://user-images.githubusercontent.com/23170160/133581654-54741761-72f7-48b3-8d96-bff2b38198a8.png)

**Comment by dmitryserbin** [comment]
Got it. I will look into this tomorrow, stay tuned.

**Comment by dmitryserbin** [comment]
Released in 1.2.980. Sorry it got broken, I wasn't expecting anyone using the task to tag builds directly. It is now fully supported and I also added notes to the docs.

**Comment by Skvorecz** [comment]
Works fine. Thank you!
