### ISSUE TITLE
Artifacts with .type in the artifact name cannot be tagged

### ISSUE THREAD

**Issue by EinmalIM** [dmitryserbin/azdev-artifacts-tagger#14]
This line removes all occurrences of ".type" from the artifact name: https://github.com/dmitryserbin/azdev-artifacts-tagger/blob/205419806cd860ee4a7ec4bf8fc7799080095aa8/Tasks/TaggerV1/helpers/taskhelper.ts#L122

Unforunately one of our artifacts has "online.typescript" in its name, so the tagger tries to use an artifact "onlinescript" which does not exist, due to the missing ".type" part in the name.

I think you should only remove the last occurence of ".type" not all.

To repro: just add an artifact to any release pipeline and name it e.g. "this.is.my.typescript.module". When you add the artifacts tagger it will fail because it cant find this.is.myscript.module.buildid

**Comment by dmitryserbin** [comment]
Merged, to be released shortly

**Comment by dmitryserbin** [comment]
Released in 1.2.980

**Comment by EinmalIM** [comment]
Version 1.2.980 is the old published one. I think you will need to increase the version number to update the marketplace version.

**Comment by dmitryserbin** [comment]
That's odd, let me look into this

**Comment by dmitryserbin** [comment]
fixed now, sorry about that

**Comment by EinmalIM** [comment]
Yes, now we see the new version 1.2.1590 which is working great for us. Thank you!
