### ISSUE TITLE
##[error]Endpoint not present: SystemVssConnection

### ISSUE THREAD

**Issue by nairsajith** [dmitryserbin/azdev-artifacts-tagger#3]
Gives the above error when running the task on a linux agent, works fine on a windows agenet

**Comment by dmitryserbin** [comment]
Thanks for reporting this, `SYSTEMVSSCONNECTION` is case sensitive on linux agents. I can resolve it pretty quickly. Will try to release the fix next day or two.

**Comment by dmitryserbin** [comment]
Fixed in v1.1.2. Sorry it took some time.
