### ISSUE TITLE
How to tag multiple artifacts in the release pipeline?

### ISSUE THREAD

**Issue by sundar85** [dmitryserbin/azdev-artifacts-tagger#6]
I have multiple artifacts used in a release pipeline and I would like to tag all. Currently, it only tags the primary artifacts.

**Comment by dmitryserbin** [comment]
Hi, thanks for the feedback. This sounds doable, let me see what I can do.

**Comment by sundar85** [comment]
I am still looking forward to this xD.

**Comment by dmitryserbin** [comment]
Thanks for reminder! #9

**Comment by dmitryserbin** [comment]
Released in 1.2.*
