### ISSUE TITLE
Tunneling socket could not be established

### ISSUE THREAD

**Issue by prabhusirpi** [dmitryserbin/azdev-artifacts-tagger#7]
The task is getting failed with below error:

Tunneling socket could not be established, statuscode=502. 

Please let me know the fix at the earliest

**Comment by prabhusirpi** [comment]
@dmitryserbin Request to look into the error

**Comment by dmitryserbin** [comment]
This looks s lot like intermittent Azure DevOps issue. Hope it is now resolved.
